### ISSUE TITLE
long lines always wrap in markdown documents

### ISSUE THREAD

**Issue by fczuardi** [zedapp/zed#495] opened 2015-01-28 12:48 UTC
When working with javascript files, and with the Word Wrap settings turned off, my long lines do not break at the wrap limit, they remain long, which is the expected behavior.

But with the same setting, if I open a markdown file containing a long line, it will always wrap no matter what your preference is setted to.

#### Steps to reproduce:
1. Open a markdown file with long lines of text
2. Turn the Editor>Word wrap preference on and off, either via preferences screen (Ctrl + ,) or command menu (Ctrl + . + search wrap) or by editing your user.json file

#### Expected behavior
The long line will visually break or not break depending on the setting

#### Actual behavior
The preference is not respected and the line always wrap

**Comment by zefhemel** [comment] 2015-01-28 13:02
Duplicate of: #333
In brief: this is by design, the markdown mode has a local overwrite of the global preference. The referenced issue shows how to disable this behavior if you want.

Please reopen if you find this a terrible mistake.

**Closed by zefhemel** 2015-01-28 13:02 UTC

**Comment by fczuardi** [comment] 2015-01-28 13:18
I don't find it a terrible mistake, just odd and unintuitive since there is a preference in the UI that does not do what it says it does. But the workaround works for me, adding:

```
    modes: {
        markdown: {
            preferences: {
                wordWrap: false
            }
        }
    },
```

to the user.json fixes it, thanks!  :)

**Comment by fczuardi** [comment] 2015-01-28 13:23
The only problem with that workaround is that the user loses the ability to toggle on/off the wrap for markdown files quickly via (Ctrl + .), but since the user never had that ability in the first place anyways she is not really "losing" anything.

**Comment by zefhemel** [comment] 2015-01-28 13:31
That's a good point, this makes this bug related to #446
